# Generated by Django 4.1.5 on 2023-01-12 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zodiac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ratio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.FloatField()),
                ('zodiac1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='zodiac1', to='api.zodiac')),
                ('zodiac2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='zodiac2', to='api.zodiac')),
            ],
        ),
    ]
